.Dd December 12, 2019
.Dt VARLPENIS 6
.Os
.Sh NAME
.Nm varlpenis
.Nd generate ASCII-art penis of arbitrary length
.Sh SYNOPSIS
.Nm
.Op Fl cfhv
.Op Fl e Ar distance
.Op Fl l Ar length
.Sh DESCRIPTION
When
.Nm
is run with no arguments, it prints a penis of random length in plaintext.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl c
Print escape sequences for colored output.  Only available if compiled with
.Dv VP_USE_COLOR .
.It Fl e Ar distance
Print a penis with
.Ar distance
number of
.So
~
.Sc
(tilde).
.It Fl f
Print fullwidth characters using UTF-8.  Only available if compiled with
.Dv VP_USE_FULLWIDTH .
.It Fl h
Print help message and exit.
.It Fl l Ar length
Print a penis with
.Ar length
number of
.So
=
.Sc
(equals).
.It Fl v
Print version information and exit.
.El
.Sh EXIT STATUS
.Nm
exits with 0 on success, and >0 if an error occurs.  If compiled with
.Dv VP_USE_SYSEXITS ,
codes from
.Xr sysexits 3
are used.
.Sh STANDARDS
.St -ansiC
.Sh AUTHORS
.An Seth Price Aq Mt sprice623@aol.com
.Sh CAVEATS
Due to the limitations of four-bit color codes, the program output (when
compiled with and using color support) may appear to only represent a
Caucasian, Oriental or other light-skinned phallus\(emor, more specifically,
Homer Simpson's erect penis with an inflamed glans (depending on your
terminal's color scheme).
.Sh BUGS
None currently known.  Report any bugs to the issue tracker at
.Lk https://www.gitlab.com/ssterling/varlpenis/issues .
